//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.17 at 06:05:44 PM CDT 
//


package com.evernote.enex;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "data",
    "mime",
    "width",
    "height",
    "duration",
    "recognition",
    "resourceAttributes",
    "alternateData"
})
@XmlRootElement(name = "resource")
public class Resource {

    @XmlElement(required = true)
    protected Data data;
    @XmlElement(required = true)
    protected String mime;
    protected String width;
    protected String height;
    protected String duration;
    protected String recognition;
    @XmlElement(name = "resource-attributes")
    protected ResourceAttributes resourceAttributes;
    @XmlElement(name = "alternate-data")
    protected AlternateData alternateData;

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link Data }
     *     
     */
    public Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link Data }
     *     
     */
    public void setData(Data value) {
        this.data = value;
    }

    /**
     * Gets the value of the mime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMime() {
        return mime;
    }

    /**
     * Sets the value of the mime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMime(String value) {
        this.mime = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidth(String value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeight(String value) {
        this.height = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDuration(String value) {
        this.duration = value;
    }

    /**
     * Gets the value of the recognition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecognition() {
        return recognition;
    }

    /**
     * Sets the value of the recognition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecognition(String value) {
        this.recognition = value;
    }

    /**
     * Gets the value of the resourceAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceAttributes }
     *     
     */
    public ResourceAttributes getResourceAttributes() {
        return resourceAttributes;
    }

    /**
     * Sets the value of the resourceAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceAttributes }
     *     
     */
    public void setResourceAttributes(ResourceAttributes value) {
        this.resourceAttributes = value;
    }

    /**
     * Gets the value of the alternateData property.
     * 
     * @return
     *     possible object is
     *     {@link AlternateData }
     *     
     */
    public AlternateData getAlternateData() {
        return alternateData;
    }

    /**
     * Sets the value of the alternateData property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlternateData }
     *     
     */
    public void setAlternateData(AlternateData value) {
        this.alternateData = value;
    }

}
