version: "3.6"
networks:
  webnet:

services:
  app:
    image: localhost:5000/recipe-app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:7000"
    networks:
      - webnet
    secrets:
      - dbUrl
  db:
    image: localhost:5000/recipe-db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - webnet
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
    secrets:
      - postgres-passwd
  admin:
    image: localhost:5000/recipe-admin
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet
    secrets:
      - dbUrl
    stdin_open: true

volumes:
  dbdata:

secrets:
  dbUrl:
    external: true
  postgres-passwd:
    external: true
