version: "3.6"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: kaaphi/recipe-app:snapshot
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:7000"
    networks:
      - webnet
    secrets:
      - dbUrl
  db:
    image: kaaphi/recipe-db:snapshot
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - webnet
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
    secrets:
      - postgres-passwd

networks:
  webnet:

volumes:
  dbdata:

secrets:
  dbUrl:
    external: true
  postgres-passwd:
    external: true
