name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      version:
      default: 'snapshot'
      required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew build

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push admin
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./recipe-admin
          file: ./recipe-admin/Dockerfile
          tags: "${{ secrets.DOCKER_REGISTRY }}/recipe-admin:${{ github.event.inputs.version }}"
      - name: Build and push app
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./recipe-app
          file: ./recipe-app/Dockerfile
          tags: "${{ secrets.DOCKER_REGISTRY }}/recipe-app:${{ github.event.inputs.version }}"
      - name: Build and push db
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./recipe-db
          file: ./recipe-db/Dockerfile
          tags: "${{ secrets.DOCKER_REGISTRY }}/recipe-db:${{ github.event.inputs.version }}"
          