name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        default: "snapshot"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      database:
        image: postgres:10.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build DB scripts with Gradle
        run: ./gradlew recipe-db:build

      - name: Migrate DB
        run: for f in ./recipe-db/build/scripts/*; do echo Running $f; psql --set ON_ERROR_STOP=on -f $f; done
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDATABASE: postgres

      - name: Build and Run Tests
        run: ./gradlew build
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push app
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./recipe-app
          file: ./recipe-app/Dockerfile
          tags: "${{ secrets.DOCKER_REGISTRY }}/recipe-app:${{ github.event.inputs.version }}"
          push: true
      
      - name: Push DB Scripts
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSHKEY }}
          source: "./recipe-db/build/scripts/*"
          target: "${{ secrets.DEPLOY_TARGET }}/${{ github.event.inputs.version }}"
          strip_components: 3
          
